site_name: Kakunin
site_description: Kakunin - E2E testing framework on steroids
site_url: https://thesoftwarehouse.github.io/Kakunin/
repo_url: https://github.com/TheSoftwareHouse/Kakunin

theme: 'material'
theme_dir: docs-theme
docs_dir: docs-src
site_dir: docs
edit_uri: edit/master/docs-src/

google_analytics: ['UA-106047429-1', 'auto']

pages:
  - Quick start: quickstart.md
  - Getting started: index.md
  - Configuration: configuration.md
  - How it works: how-it-works.md
  - Built-in steps: steps.md
  - Matchers: matchers.md
  - Transformers: transformers.md
  - Performance testing: performance-testing.md
  - Extending Kakunin: extending.md

markdown_extensions:
  - codehilite

extra:
  meta_image: assets/kakunin-header.png
  social:
    - type: 'facebook'
      link: 'https://www.facebook.com/TheSoftwareHousePL/'
    - type: 'twitter'
      link: 'https://twitter.com/realtsh'
    - type: 'circle-o-notch'
      link: 'https://clutch.co/profile/software-house'
